---
#- name: Define version GP
#  ansible.builtin.set_fact:
#    gp_ver: "{{ lookup('file', '../../../VERSION') }}"

- name: Create /usr/local/greenplum
  ansible.builtin.file:
    path: "{{ gphome }}-7.1.0"
    state: directory
    owner: "{{ cluster_admin_user }}"
    group: "{{ cluster_admin_user }}"
    mode: "0755"
  tags:
    - add_host

- name: Install Greenplum
  ansible.builtin.unarchive:
    src: "gp.tar.gz"
    dest: "{{ gphome }}-7.1.0"
    owner: "{{ cluster_admin_user }}"
    group: "{{ cluster_admin_user }}"
    mode: "0755"
  tags:
    - add_host

- name: Create symlink GP directory
  ansible.builtin.file:
    src: "{{ gphome }}-7.1.0"
    dest: "{{ gphome }}"
    owner: "{{ cluster_admin_user }}"
    group: "{{ cluster_admin_user }}"
    state: link
  tags:
    - add_host

- name: Adding Greenplum path profile to profile of {{ cluster_admin_user }}
  ansible.builtin.lineinfile:
    path: /home/{{ cluster_admin_user }}/.bashrc
    regexp: '.*/usr/lib/local/greenplum/greenplum_path.sh.*'
    line: 'source {{ gphome }}/greenplum_path.sh'
  tags:
    - add_host

- name: Getting priv key
  ansible.builtin.fetch:
    src: "/home/{{ cluster_admin_user }}/.ssh/{{ item }}"
    dest: "tmp/{{ item }}"
    flat: true
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  loop:
    - id_rsa
    - id_rsa.pub
  tags:
    - add_host

- name: Distributing private key across cluster
  ansible.builtin.copy:
    src: "tmp/{{ item.name }}"
    dest: "/home/{{ cluster_admin_user }}/.ssh/{{ item.name }}"
    group: "{{ cluster_admin_user }}"
    owner: "{{ cluster_admin_user }}"
    mode: "{{ item.mode }}"
  loop:
    - {name: "id_rsa", mode: '0600'}
    - {name: "id_rsa.pub", mode: '0644'}
  tags:
    - add_host

- name: Run tasks/initializing.yml
  ansible.builtin.include_tasks:
    file: initializing.yml
  #tags:
  #  - add_host
...
